---
- name: Create the user
  user:
    name: "{{user}}"
    password: "{{password | password_hash('sha512')}}"
    group: wheel
    createhome: yes
    home: "/home/{{user}}"
  become: true

- name: Check if the user name was created
  shell: |
    cd ..
    ls | grep {{user}}
  args:
    executable: /bin/bash
  register: output

- name: User Created message
  debug:
    msg: "user: {{output.stdout}} created"
  when: output.stdout == user

- name: Check user created failed
  debug:
    msg: "Failed to create {{user}}"
  when: output.stdout != user